version: "3.9"

services:
  users_service:
    build: .
    container_name: users_service
    ports:
      - "8001:8000"   # Host 8001 --> Container 8000
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: friend_request_db
    depends_on:
      - mysql_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: friend_request_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: